# Bank Loan Risk Analysis

## Objective
The objective of this project is to analyze bank loan applicant data to understand customer behavior, identify patterns, and discover factors affecting loan approval and default risk.

### Tools Used
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/loan_data.csv")

In [4]:
df.head()

,candidate_id,country,organization,interest_rate,unpaid_principal_bal,loan_term,origination_date,first_payment_date,loan_to_value,number_of_borrowers,...,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13
0,2.680000e+11,Z,"Turner, Baldwin and Rhodes",4.250,214000,360,01-03-2012,May-12,95,1,...,0,0,0,1,0,0,0,0,0,1
1,6.730000e+11,Y,"Swanson, Newton and Miller",4.875,144000,360,01-01-2012,Mar-12,72,1,...,0,0,0,0,0,0,0,1,0,1
2,7.430000e+11,Z,Thornton-Davis,3.250,366000,180,01-01-2012,Mar-12,49,1,...,0,0,0,0,0,0,0,0,0,1
3,6.010000e+11,X,OTHER,4.750,135000,360,01-02-2012,Apr-12,46,2,...,0,0,0,0,0,1,1,1,1,1
4,2.740000e+11,X,OTHER,4.750,124000,360,01-02-2012,Apr-12,80,1,...,3,4,5,6,7,8,9,10,11,1

In [5]:
df.shape

(116058, 29)

In [6]:
df.columns

Index(['candidate_id', 'country', 'organization', 'interest_rate',
       'unpaid_principal_bal', 'loan_term', 'origination_date',
       'first_payment_date', 'loan_to_value', 'number_of_borrowers',
       'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'E1',
       'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'E10', 'E11', 'E12',
       'E13'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116058 entries, 0 to 116057
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   candidate_id              116058 non-null  float64
 1   country                   116058 non-null  object
 2   organization              116058 non-null  object
 3   interest_rate             116058 non-null  float64
 4   unpaid_principal_bal      116058 non-null  int64
 5   loan_term                 116058 non-null  int64
 6   origination_date          116058 non-null  object
 7   first_payment_date        116058 non-null  object
 8   loan_to_value             116058 non-null  int64
 9   number_of_borrowers       116058 non-null  int64
 10  debt_to_income_ratio      116058 non-null  int64
 11  borrower_credit_score     116058 non-null  int64
 12  loan_purpose              116058 non-null  object
 13  insurance_percent         116058 non-null  int64
 14  co-borrower_credit_score  116058 non-null  int64
 15  insurance_type            116058 non-null  int64
 16  E1                        116058 non-null  int64
 17  E2                        116058 non-null  int64
 18  E3                        116058 non-null  int64
 19  E4                        116058 non-null  int64
 20  E5                        116058 non-null  int64
 21  E6                        116058 non-null  int64
 22  E7                        116058 non-null  int64
 23  E8                        116058 non-null  int64
 24  E9                        116058 non-null  int64
 25  E10                       116058 non-null  int64
 26  E11                       116058 non-null  int64
 27  E12                       116058 non-null  int64
 28  E13                       116058 non-null  int64
dtypes: float64(2), int64(22), object(5)
memory usage: 25.7+ MB

In [8]:
df.describe()

,candidate_id,interest_rate,unpaid_principal_bal,loan_term,loan_to_value,number_of_borrowers,debt_to_income_ratio,borrower_credit_score,insurance_percent,co-borrower_credit_score,...,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13
count,1.160580e+05,116058.000000,1.160580e+05,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,...,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000,116058.000000
mean,5.494154e+11,3.868961,2.082262e+05,292.280997,67.431939,1.593186,30.742293,769.926778,2.786288,459.611565,...,0.002180,0.003533,0.003421,0.004162,0.004825,0.005359,0.006617,0.007109,0.008065,0.005480
std,2.597569e+11,0.461020,1.146851e+05,89.762415,17.291719,0.491242,9.730798,42.210706,8.096464,381.946926,...,0.062161,0.082638,0.087553,0.100961,0.113128,0.128242,0.148430,0.162884,0.178128,0.073824
min,1.000000e+11,2.250000,1.100000e+04,60.000000,6.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.240000e+11,3.500000,1.200000e+05,180.000000,57.000000,1.000000,23.000000,751.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.490000e+11,3.875000,1.830000e+05,360.000000,72.000000,2.000000,31.000000,782.000000,0.000000,740.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.740000e+11,4.125000,2.780000e+05,360.000000,80.000000,2.000000,39.000000,800.000000,0.000000,791.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000e+12,6.750000,1.200000e+06,360.000000,97.000000,2.000000,64.000000,840.000000,40.000000,836.000000,...,6.000000,7.000000,8.000000,9.000000,10.000000,11.000000,12.000000,13.000000,14.000000,1.000000

In [9]:
df.isnull().sum()

candidate_id                0
country                     0
organization                0
interest_rate               0
unpaid_principal_bal        0
loan_term                   0
origination_date            0
first_payment_date          0
loan_to_value               0
number_of_borrowers         0
debt_to_income_ratio        0
borrower_credit_score       0
loan_purpose                0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
E1                          0
E2                          0
E3                          0
E4                          0
E5                          0
E6                          0
E7                          0
E8                          0
E9                          0
E10                         0
E11                         0
E12                         0
E13                         0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.nunique()

candidate_id                901
country                       3
organization                 19
interest_rate               923
unpaid_principal_bal        646
loan_term                   140
origination_date              3
first_payment_date            4
loan_to_value                92
number_of_borrowers           2
debt_to_income_ratio         58
borrower_credit_score       221
loan_purpose                  3
insurance_percent            14
co-borrower_credit_score    216
insurance_type                2
E1                            4
E2                            5
E3                            6
E4                            7
E5                            8
E6                            9
E7                           10
E8                           10
E9                           11
E10                          12
E11                          13
E12                          13
E13                           2
dtype: int64

In [12]:
df.isnull().sum()

candidate_id                0
country                     0
organization                0
interest_rate               0
unpaid_principal_bal        0
loan_term                   0
origination_date            0
first_payment_date          0
loan_to_value               0
number_of_borrowers         0
debt_to_income_ratio        0
borrower_credit_score       0
loan_purpose                0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
E1                          0
E2                          0
E3                          0
E4                          0
E5                          0
E6                          0
E7                          0
E8                          0
E9                          0
E10                         0
E11                         0
E12                         0
E13                         0
dtype: int64

In [13]:
df.isnull().sum().sort_values(ascending=False)

candidate_id                0
country                     0
organization                0
interest_rate               0
unpaid_principal_bal        0
loan_term                   0
origination_date            0
first_payment_date          0
loan_to_value               0
number_of_borrowers         0
debt_to_income_ratio        0
borrower_credit_score       0
loan_purpose                0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
E1                          0
E2                          0
E3                          0
E4                          0
E5                          0
E6                          0
E7                          0
E8                          0
E9                          0
E10                         0
E11                         0
E12                         0
E13                         0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df = df.drop_duplicates()

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.dtypes

candidate_id                float64
country                      object
organization                 object
interest_rate               float64
unpaid_principal_bal          int64
loan_term                     int64
origination_date             object
first_payment_date           object
loan_to_value                 int64
number_of_borrowers           int64
debt_to_income_ratio          int64
borrower_credit_score         int64
loan_purpose                 object
insurance_percent             int64
co-borrower_credit_score      int64
insurance_type                int64
E1                            int64
E2                            int64
E3                            int64
E4                            int64
E5                            int64
E6                            int64
E7                            int64
E8                            int64
E9                            int64
E10                           int64
E11                           int64
E12                           int64
E13                           int64
dtype: object

In [18]:
df.columns

Index(['candidate_id', 'country', 'organization', 'interest_rate',
       'unpaid_principal_bal', 'loan_term', 'origination_date',
       'first_payment_date', 'loan_to_value', 'number_of_borrowers',
       'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'E1',
       'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'E10', 'E11', 'E12',
       'E13'],
      dtype='object')

In [19]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [20]:
df.columns

Index(['candidate_id', 'country', 'organization', 'interest_rate',
       'unpaid_principal_bal', 'loan_term', 'origination_date',
       'first_payment_date', 'loan_to_value', 'number_of_borrowers',
       'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'e1',
       'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'e10', 'e11', 'e12',
       'e13'],
      dtype='object')

In [21]:
df.nunique()

candidate_id                901
country                       3
organization                 19
interest_rate               923
unpaid_principal_bal        646
loan_term                   140
origination_date              3
first_payment_date            4
loan_to_value                92
number_of_borrowers           2
debt_to_income_ratio         58
borrower_credit_score       221
loan_purpose                  3
insurance_percent            14
co-borrower_credit_score    216
insurance_type                2
e1                            4
e2                            5
e3                            6
e4                            7
e5                            8
e6                            9
e7                           10
e8                           10
e9                           11
e10                          12
e11                          13
e12                          13
e13                           2
dtype: int64

In [23]:
df["loan_to_value"].value_counts()

loan_to_value
80    22364
75     8231
95     4374
70     3393
90     3303
      ...
10       28
9        11
8        10
7         8
6         5
Name: count, Length: 92, dtype: int64